spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    bus:
      enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order
#    username: denisgithuku
#    password: 5ub05p4rg3
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://configserver:8888
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: ""
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#server:
#  port: 8083
#logging:
#  pattern:
#    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
#  level:
#    springframework: DEBUG
#    web: DEBUG
#    org:
#      hibernate: TRACE
#      springframework:
#        security:
#          web:
#            FilterChainProxy: ${SPRING_FILTER_CHAIN_LOGGING_LEVEL:DEBUG}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

