spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DenisGithuku/ecommerce-microservices-configuration
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
#    inetutils:
#      preferred-networks:
#        - 127.0.0.1

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}
    connection-timout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

server:
  port: 8888